apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  template:
    metadata:
      name: httpd-frontend
      labels:
        name: webapp
    spec:
      containers:
      - name: httpd-frontend
        image: httpd:2.4-alpine
  replicas: 3
  selector:
    matchLabels:
      name: webapp
