apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels: 
      environment: test
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        tier: frontend          
        environment: test
    spec:
      containers:
      - name: nginx
        image: nginx
